import { Poppins as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import React from "react";

const fontSans  = FontSans ({ 
  subsets: ["latin"],
  weight: ['400', '500', '600'],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: Readonly<React.ReactNode>;
}

export default function RootLayout({children}:Props) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body className={cn(
          "min-h-screen bg-background-alt font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
